### ISSUE TITLE
무비로그 페이지

### ISSUE THREAD

**Issue by stakbucks** [IT-NOVATION/FrontEnd#37]
### 📘 이슈 내용
<img width="557" alt="스크린샷 2023-06-25 오후 3 33 13" src="https://github.com/IT-NOVATION/FrontEnd/assets/107744534/3e05b2e3-345a-4a04-99d4-b7829d82a853">

<img width="562" alt="스크린샷 2023-06-25 오후 3 33 47" src="https://github.com/IT-NOVATION/FrontEnd/assets/107744534/338ae728-a57a-4fd0-9042-d4cd6eaa55fa">

<br/>

### 📝 TODO
- [x] 무비로그 페이지
- [x] 뱃지 컴포넌트 만들기
- [x] 프로필 사진 컴포넌트 만들기
- [x] 프로필 수정 모달 만들기
- [ ] 서버 연동

<br/><br/>
