### ISSUE TITLE
네비게이션 바 검색 창 만들기

### ISSUE THREAD

**Issue by ZUITOPIA** [IT-NOVATION/FrontEnd#41]
### 📘 이슈 내용
내용을 적으세요.

<br/>

### 📝 TODO
- [x] 할 일 1 : nav 바 App.tsx 파일에서 실행하도록 위치 변경
- [x] 할 일 2 : 검색 icon 클릭 시 네비게이션 바 넓어지고 검색창 보이게
- [x] 할 일 3 : UI 파일 디자인시스템 수정해서 적용
- [x] 할 일 4 : 검색 결과 페이지 제작 (검색창)
- [ ] 할 일 5 : 유저 / 영화 드롭다운 제작
- [ ] 할 일 6 : api 연결
- [x] 할 일 7 : 인기검색어 배열 자체제작해서 랜덤 보여주기
- [ ] 할 일 8 : 유저 / 영화 에 따라 placeholder 다르게 (검색 다르게)

<br/><br/>
