### ISSUE TITLE
메인페이지 수정

### ISSUE THREAD

**Issue by stakbucks** [IT-NOVATION/FrontEnd#57]
### 📘 이슈 내용

메인페이지 수정하기

<br/>

### 📝 TODO
- [x] 별점 계산 오류 수정
- [ ] 본인 프로필/ 팔로우 여부에 따라 버튼 다르게 보이도록 수정
- [x] 랜딩 페이지 없애기

<br/><br/>
