### ISSUE TITLE
디테일한 부분 수정하기

### ISSUE THREAD

**Issue by stakbucks** [IT-NOVATION/FrontEnd#74]
### 📘 이슈 내용

- 디테일한 부분 수정하기

<br/>

### 📝 TODO
- [x] 댓글 입력 여부 확인
- [x] 리뷰 읽기 작성자 누르면 무비로그로
- [x] 파비콘 적용시키기
- [x] 모바로 접속시 안내 문구 띄우기
- [x] 메인페이지 ‘팔로우’버튼 클릭시 로그인 체크

<br/><br/>
