### ISSUE TITLE
7/27 디테일 수정

### ISSUE THREAD

**Issue by stakbucks** [IT-NOVATION/FrontEnd#81]
### 📘 이슈 내용

자잘한 오류들 수정하기

<br/>

### 📝 TODO
- [x] 무비로그, 메인페이지-리뷰타임, 개별영화페이지의 리뷰 미리보기에 댓글 갯수 제대로 반영
- [x] 리뷰읽기 페이지에 관람일자 반영
- [x] 개별영화페이지 '리뷰작성'버튼 클릭 제대로 안되는 문제 해결
- [x] 리뷰작성 페이지에서 영화정보 가져오는 요청 캐시타임 없애서 버그 수정
- [x] 리뷰작성 페이지에 영화 개봉일자 제대로 반영
- [x] 개별영화페이지에서 배우 목록 길어지면 레이아웃 깨지는 문제 해결
- [x] 개별영화메인페이지 영화 정보에 장로 2번 나오는 거 수정
- [x] 프로필편집, 회원가입-프로필정보 입력에서 한줄소개 글자수 40자로 제한하기
- [x] 네비바 아이콘 수정+무비로그 버튼 디자인 수정
- [x] 무비서치 이미지 로딩시 스케렐톤 ui 적용

<br/><br/>
