### ISSUE TITLE
여러가지 UX 개선사항

### ISSUE THREAD

**Issue by ZUITOPIA** [IT-NOVATION/FrontEnd#88]
### 📘 이슈 내용
내용을 적으세요.

<br/>

### 📝 TODO
- [ ] 할 일 1 : 검색창에 입력 후 페이지 넘어갈 때 검색어가 검색창에 남아있도록 하기
- [ ] 할 일 2 : 무한스크롤 시 창을 너무 많이 내렸을 때 다시 스크롤로 올라가기 번거로우니 우측하단 UP 버튼 클릭으로 바로 맨 위로 올라갈 수 있도록 하기
- [ ] 할 일 3 : 회원가입 완료 시 바로 로그인 모달창 띄우기
- [ ] 할 일 4 : 포스터 나오는 모든 부분 suspense로 skeleton 처리 (예. 무비타임 미리보기 부분 포스터 아직 찢어짐)
- [ ] 할 일 5 : 리뷰타임 보여주는 유저 고정 없애기

<br/><br/>
